---
- name: Import RedHat
  ansible.builtin.import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Import Debian
  ansible.builtin.import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
