---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: ensure sensu is installed
      ansible.builtin.apt:
        name: sensu-go-backend
        state: latest

    # curl http://127.0.0.1:8080/health
