---
# curl http://127.0.0.1:8080/health
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Show default IPv4 address
      ansible.builtin.debug:
        var: ansible_facts['default_ipv4']['address']
    - name: Check if connection still works
      ansible.builtin.ping:

    - name: Check web ui
      ansible.builtin.uri:
        url: "http://{{ ansible_facts['default_ipv4']['address'] }}:8080/health"
        return_content: true
      register: sensu_check_web_ui
      ignore_errors: true
