---
# curl http://127.0.0.1:8080/health
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if connection still works
      ansible.builtin.ping:

    - name: check web ui
      ansible.builtin.uri:
        url: "http://127.0.0.1:8080/health"
        return_content: yes
      register: sensu_check_web_ui
      failed_when:
        - "'Sensu' not in sensu_check_web_ui.content"
